# Generated by Django 5.0.2 on 2024-03-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
